### ISSUE TITLE
Indentation Issue leading to unreachable return statement

### ISSUE THREAD

**Issue by Suyious** [costomato/swar-sthaanaantaran-saadhan#5]
https://github.com/costomato/swar-sthaanaantaran-saadhan/blob/3b862fe0f8e47579aced55998ff1ec7c410b7af7/index.html#L332-L335

In [index.html:334](https://github.com/costomato/swar-sthaanaantaran-saadhan/blob/3b862fe0f8e47579aced55998ff1ec7c410b7af7/index.html#L334), the return statement should be inside the else block
```javascript
   else {
        result = indianToWestern(pitch) + octave;
        return result;
   }
   return indianToWestern(pitch) + octave;
```

**Comment by costomato** [comment]
🤔 ok, I'll see
